import 'package:flutter/material.dart';
import 'package:intl/intl.dart';
import 'package:share_plus/share_plus.dart';
import '../utils/constants.dart';
import '../services/school_db_service.dart';

class AttendanceScreen extends StatefulWidget {
  final String schoolId;
  final String className;
  const AttendanceScreen({super.key, required this.schoolId, required this.className});

  @override
  State<AttendanceScreen> createState() => _AttendanceScreenState();
}

class _AttendanceScreenState extends State<AttendanceScreen> {
  DateTime _selectedDate = DateTime.now();
  bool _showStats = false;
  Map<String, dynamic> _currentAttendance = {};
  bool _attendanceLoaded = false;

  @override
  void initState() {
    super.initState();
    SchoolDbService.instance.refreshStudents(
      schoolId: widget.schoolId,
      className: widget.className,
    );
    _loadAttendance();
  }

  Future<void> _loadAttendance() async {
    final records = await SchoolDbService.instance.getAttendance(
      schoolId: widget.schoolId,
      className: widget.className,
      date: _selectedDate,
    );
    if (mounted) {
      setState(() {
        _currentAttendance = Map<String, dynamic>.from(records);
        _attendanceLoaded = true;
      });
    }
  }

  Future<void> _shareMonthlyReport() async {
    final pickedMonth = await showDatePicker(
      context: context,
      initialDate: _selectedDate,
      firstDate: DateTime(2000),
      lastDate: DateTime.now(),
      initialDatePickerMode: DatePickerMode.year,
      helpText: 'SELECT MONTH FOR REPORT',
    );

    if (pickedMonth == null) return;

    if (!mounted) return;
    showDialog(
      context: context,
      barrierDismissible: false,
      builder: (context) => const Center(child: CircularProgressIndicator()),
    );

    try {
      final monthDisplay = DateFormat('MMMM yyyy').format(pickedMonth);
      final students = await SchoolDbService.instance.getStudents(
        schoolId: widget.schoolId,
        className: widget.className,
      );

      if (students.isEmpty) {
        if (mounted) Navigator.pop(context);
        if (mounted) ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content: Text('No students found!')));
        return;
      }

      final attendanceRecords = await SchoolDbService.instance.getAllAttendance(
        schoolId: widget.schoolId,
        className: widget.className,
      );

      if (mounted) Navigator.pop(context);

      Map<String, int> studentPresentCount = {};
      for (var s in students) {
        studentPresentCount[s['id'] as String] = 0;
      }

      int totalDaysWithRecords = 0;
      for (var record in attendanceRecords) {
        final date = DateTime.parse(record['date'] as String);
        if (date.year == pickedMonth.year && date.month == pickedMonth.month) {
          totalDaysWithRecords++;
          final dayRecords = record['records'] as Map<String, dynamic>;
          for (var s in students) {
            final sid = s['id'] as String;
            if (dayRecords[sid] == true) {
              studentPresentCount[sid] = (studentPresentCount[sid] ?? 0) + 1;
            }
          }
        }
      }

      if (totalDaysWithRecords == 0) {
        if (mounted) {
          ScaffoldMessenger.of(context).showSnackBar(
            const SnackBar(content: Text('No attendance records found for this month.')),
          );
        }
        return;
      }

      final report = StringBuffer();
      report.writeln('📊 *ATTENDANCE REPORT - $monthDisplay*');
      report.writeln('-----------------------------------');
      report.writeln('Total Working Days: $totalDaysWithRecords');
      report.writeln('-----------------------------------');

      for (var s in students) {
        final sid = s['id'] as String;
        final name = s['name'];
        final count = studentPresentCount[sid] ?? 0;
        final percent = ((count / totalDaysWithRecords) * 100).toStringAsFixed(1);
        report.writeln('• $name: $count/$totalDaysWithRecords ($percent%)');
      }

      report.writeln('-----------------------------------');
      report.writeln('Generated by My School App');

      await Share.share(report.toString(), subject: 'Monthly Attendance Report');
    } catch (e) {
      if (mounted) {
        if (Navigator.canPop(context)) Navigator.pop(context);
        ScaffoldMessenger.of(context).showSnackBar(SnackBar(content: Text('Error generating report: $e')));
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Attendance - ${widget.className}'),
        actions: [
          IconButton(
            icon: Icon(_showStats ? Icons.calendar_today : Icons.bar_chart),
            onPressed: () => setState(() => _showStats = !_showStats),
            tooltip: _showStats ? 'Daily Attendance' : 'Monthly Stats',
          ),
          IconButton(
            icon: const Icon(Icons.share),
            onPressed: _shareMonthlyReport,
            tooltip: 'Share Monthly Report',
          ),
        ],
      ),
      body: Column(
        children: [
          Padding(
            padding: const EdgeInsets.all(16.0),
            child: Row(
              mainAxisAlignment: MainAxisAlignment.spaceBetween,
              children: [
                Text(
                  _showStats
                      ? 'Month: ${DateFormat('MMMM yyyy').format(_selectedDate)}'
                      : 'Date: ${DateFormat('dd-MM-yyyy').format(_selectedDate)}',
                  style: const TextStyle(fontSize: 16, fontWeight: FontWeight.bold, color: Color(0xFF004D40)),
                ),
                TextButton.icon(
                  onPressed: () async {
                    final date = await showDatePicker(
                      context: context,
                      initialDate: _selectedDate,
                      firstDate: DateTime(2000),
                      lastDate: DateTime.now(),
                    );
                    if (date != null) {
                      setState(() {
                        _selectedDate = date;
                        _attendanceLoaded = false;
                      });
                      await _loadAttendance();
                    }
                  },
                  icon: const Icon(Icons.edit_calendar),
                  label: const Text('Change'),
                ),
              ],
            ),
          ),
          Expanded(
            child: StreamBuilder<List<Map<String, dynamic>>>(
              stream: SchoolDbService.instance.watchStudents(
                schoolId: widget.schoolId,
                className: widget.className,
              ),
              builder: (context, studentSnapshot) {
                if (!studentSnapshot.hasData) return const Center(child: CircularProgressIndicator());
                final students = studentSnapshot.data!;
                if (students.isEmpty) return const Center(child: Text('No students found in this class.'));

                if (_showStats) {
                  return _StatsList(
                    students: students,
                    schoolId: widget.schoolId,
                    className: widget.className,
                    selectedDate: _selectedDate,
                  );
                }

                if (!_attendanceLoaded) return const Center(child: CircularProgressIndicator());

                return ListView.builder(
                  itemCount: students.length,
                  itemBuilder: (context, index) {
                    final student = students[index];
                    final studentId = student['id'] as String;
                    final studentName = student['name'] as String;
                    final gender = student['gender'] ?? 'Boy';
                    final isPresent = _currentAttendance[studentId] == true;

                    return CheckboxListTile(
                      title: Text(
                        studentName,
                        style: TextStyle(
                          fontSize: 16,
                          fontWeight: FontWeight.w500,
                          color: gender == 'Girl' ? AppColors.girlColor : Colors.black87,
                        ),
                      ),
                      secondary: CircleAvatar(
                        backgroundColor: gender == 'Girl'
                            ? (isPresent ? AppColors.girlColor : AppColors.girlColorLight.withValues(alpha: 0.3))
                            : (isPresent ? Colors.green : Colors.grey.shade300),
                        child: Icon(
                          isPresent ? Icons.check : (gender == 'Girl' ? Icons.female : Icons.person),
                          color: isPresent ? Colors.white : (gender == 'Girl' ? AppColors.girlColor : Colors.grey),
                        ),
                      ),
                      value: isPresent,
                      activeColor: const Color(0xFF004D40),
                      onChanged: (val) async {
                        setState(() => _currentAttendance[studentId] = val);
                        await SchoolDbService.instance.saveAttendance(
                          schoolId: widget.schoolId,
                          className: widget.className,
                          date: _selectedDate,
                          records: _currentAttendance,
                        );
                      },
                    );
                  },
                );
              },
            ),
          ),
        ],
      ),
    );
  }
}

class _StatsList extends StatelessWidget {
  final List<Map<String, dynamic>> students;
  final String schoolId;
  final String className;
  final DateTime selectedDate;

  const _StatsList({
    required this.students,
    required this.schoolId,
    required this.className,
    required this.selectedDate,
  });

  @override
  Widget build(BuildContext context) {
    return FutureBuilder<List<Map<String, dynamic>>>(
      future: SchoolDbService.instance.getAllAttendance(schoolId: schoolId, className: className),
      builder: (context, snapshot) {
        if (!snapshot.hasData) return const Center(child: CircularProgressIndicator());

        int totalDaysInMonth = 0;
        final presentCounts = <String, int>{};

        for (var record in snapshot.data!) {
          final date = DateTime.parse(record['date'] as String);
          if (date.year == selectedDate.year && date.month == selectedDate.month) {
            totalDaysInMonth++;
            final dayRecords = record['records'] as Map<String, dynamic>;
            for (var student in students) {
              final sid = student['id'] as String;
              if (dayRecords[sid] == true) {
                presentCounts[sid] = (presentCounts[sid] ?? 0) + 1;
              }
            }
          }
        }

        return ListView.builder(
          itemCount: students.length,
          itemBuilder: (context, index) {
            final student = students[index];
            final sid = student['id'] as String;
            final gender = student['gender'] ?? 'Boy';
            final count = presentCounts[sid] ?? 0;
            final percent = totalDaysInMonth > 0 ? (count / totalDaysInMonth * 100).toStringAsFixed(1) : '0';

            return Card(
              margin: const EdgeInsets.symmetric(horizontal: 16, vertical: 8),
              child: ListTile(
                leading: CircleAvatar(
                  backgroundColor: gender == 'Girl' ? AppColors.girlColorLight : AppColors.primaryColor,
                  child: Text(student['name'][0].toUpperCase(), style: const TextStyle(color: Colors.white)),
                ),
                title: Text(
                  student['name'],
                  style: TextStyle(
                    fontWeight: FontWeight.bold,
                    color: gender == 'Girl' ? AppColors.girlColor : Colors.black87,
                  ),
                ),
                subtitle: Text('Present: $count / $totalDaysInMonth days'),
                trailing: Column(
                  mainAxisAlignment: MainAxisAlignment.center,
                  children: [
                    Text('$percent%', style: const TextStyle(fontWeight: FontWeight.bold, color: Colors.teal, fontSize: 16)),
                    const Text('Attendance', style: TextStyle(fontSize: 10)),
                  ],
                ),
                onTap: () => Navigator.push(
                  context,
                  MaterialPageRoute(
                    builder: (context) => StudentAttendanceDetailScreen(
                      studentId: sid,
                      studentName: student['name'],
                      gender: gender,
                      allAttendance: snapshot.data!,
                    ),
                  ),
                ),
              ),
            );
          },
        );
      },
    );
  }
}

class StudentAttendanceDetailScreen extends StatelessWidget {
  final String studentId;
  final String studentName;
  final String gender;
  final List<Map<String, dynamic>> allAttendance;

  const StudentAttendanceDetailScreen({
    super.key,
    required this.studentId,
    required this.studentName,
    required this.gender,
    required this.allAttendance,
  });

  @override
  Widget build(BuildContext context) {
    final monthlyAttendance = <String, List<DateTime>>{};
    for (var record in allAttendance) {
      final dayRecords = record['records'] as Map<String, dynamic>;
      if (dayRecords[studentId] == true) {
        final date = DateTime.parse(record['date'] as String);
        final monthKey = DateFormat('MMMM yyyy').format(date);
        monthlyAttendance[monthKey] = (monthlyAttendance[monthKey] ?? [])..add(date);
      }
    }

    final sortedMonths = monthlyAttendance.keys.toList()
      ..sort((a, b) => DateFormat('MMMM yyyy').parse(b).compareTo(DateFormat('MMMM yyyy').parse(a)));

    return Scaffold(
      appBar: AppBar(
        title: Text(
          studentName,
          style: TextStyle(
            color: gender == 'Girl' ? AppColors.girlColor : Colors.white,
            fontWeight: FontWeight.bold,
          ),
        ),
        foregroundColor: gender == 'Girl' ? AppColors.girlColor : Colors.white,
        actions: [
          IconButton(
            icon: const Icon(Icons.share),
            onPressed: () => _shareIndividualReport(studentName, monthlyAttendance),
          ),
        ],
      ),
      body: sortedMonths.isEmpty
          ? const Center(child: Text('No attendance records found for this student.'))
          : ListView.builder(
              padding: const EdgeInsets.all(16),
              itemCount: sortedMonths.length,
              itemBuilder: (context, index) {
                final month = sortedMonths[index];
                final dates = monthlyAttendance[month]!;
                return Card(
                  margin: const EdgeInsets.only(bottom: 16),
                  child: ExpansionTile(
                    title: Text(month, style: const TextStyle(fontWeight: FontWeight.bold)),
                    subtitle: Text('Present: ${dates.length} days'),
                    children: [
                      Padding(
                        padding: const EdgeInsets.all(16.0),
                        child: Wrap(
                          spacing: 8,
                          runSpacing: 8,
                          children: dates
                              .map((date) => Chip(
                                    label: Text(DateFormat('dd').format(date)),
                                    backgroundColor: Colors.green.shade100,
                                  ))
                              .toList(),
                        ),
                      ),
                    ],
                  ),
                );
              },
            ),
    );
  }

  void _shareIndividualReport(String name, Map<String, List<DateTime>> records) {
    final sb = StringBuffer();
    sb.writeln('📊 *ATTENDANCE REPORT: $name*');
    sb.writeln('-----------------------------------');

    records.forEach((month, dates) {
      sb.writeln('\n📅 *$month*');
      sb.writeln('Total Days Present: ${dates.length}');
      sb.writeln('Dates: ${dates.map((d) => DateFormat('dd').format(d)).join(', ')}');
    });

    sb.writeln('\n-----------------------------------');
    sb.writeln('Generated by My School App');

    Share.share(sb.toString());
  }
}
